CREATE TABLE METRIC(
   ID BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY (START 1) PRIMARY KEY,
   TYPE VARCHAR(256) NOT NULL,
   VALUE REAL NOT NULL
);

INSERT INTO METRIC(TYPE, VALUE)
VALUES
    ('SIMPLE_METRIC', 1.123),
    ('SIMPLE_METRIC', 2.456),
    ('SIMPLE_METRIC', 3.789);