package com.ucl.ADA.metric_calculator.metrics;

public enum MetricTypes {
    NUMBER_OF_ATTRIBUTE_INVOCATIONS_INCOMING,
    NUMBER_OF_ATTRIBUTE_INVOCATIONS_OUTGOING,

    NUMBER_OF_METHOD_INVOCATIONS_INCOMING,
    NUMBER_OF_METHOD_INVOCATIONS_OUTGOING,

    NUMBER_OF_PACKAGE_IMPORTS_INCOMING,
    NUMBER_OF_PACKAGE_IMPORTS_OUTGOING,

    NUMBER_OF_CONSTRUCTOR_INVOCATIONS_INCOMING,
    NUMBER_OF_CONSTRUCTOR_INVOCATIONS_OUTGOING,

    BIDIRECTIONAL_NUMBER_OF_ATTRIBUTE_INVOCATIONS,

    BIDIRECTIONAL_NUMBER_OF_METHOD_INVOCATIONS,

    BIDIRECTIONAL_NUMBER_OF_PACKAGE_IMPORTS,

    BIDIRECTIONAL_NUMBER_OF_CONSTRUCTOR_INVOCATIONS
}
