package com.ucl.ADA.metric_calculator.metrics_structure;

public enum ClassMetricTypes {
    NUMBER_OF_CLASS_ATTRIBUTE_INVOCATIONS_INCOMING,
    NUMBER_OF_CLASS_ATTRIBUTE_INVOCATIONS_OUTGOING,

    NUMBER_OF_CLASS_METHOD_INVOCATIONS_INCOMING,
    NUMBER_OF_CLASS_METHOD_INVOCATIONS_OUTGOING,

    NUMBER_OF_CLASS_PACKAGE_IMPORTS_INCOMING,
    NUMBER_OF_CLASS_PACKAGE_IMPORTS_OUTGOING,

    NUMBER_OF_CLASS_CONSTRUCTOR_INVOCATIONS_INCOMING,
    NUMBER_OF_CLASS_CONSTRUCTOR_INVOCATIONS_OUTGOING,

    BIDIRECTIONAL_NUMBER_OF_CLASS_ATTRIBUTE_INVOCATIONS,

    BIDIRECTIONAL_NUMBER_OF_CLASS_METHOD_INVOCATIONS,

    BIDIRECTIONAL_NUMBER_OF_CLASS_PACKAGE_IMPORTS,

    BIDIRECTIONAL_NUMBER_OF_CLASS_CONSTRUCTOR_INVOCATIONS
}
