package com.ucl.ADA.model.metrics.relation_metrics;

public enum RelationMetricType {
    NUMBER_OF_RELATION_ATTRIBUTE_INVOCATIONS_INCOMING,
    NUMBER_OF_RELATION_ATTRIBUTE_INVOCATIONS_OUTGOING,

    NUMBER_OF_RELATION_METHOD_INVOCATIONS_INCOMING,
    NUMBER_OF_RELATION_METHOD_INVOCATIONS_OUTGOING,

    NUMBER_OF_RELATION_PACKAGE_IMPORTS_INCOMING,
    NUMBER_OF_RELATION_PACKAGE_IMPORTS_OUTGOING,

    NUMBER_OF_RELATION_CONSTRUCTOR_INVOCATIONS_INCOMING,
    NUMBER_OF_RELATION_CONSTRUCTOR_INVOCATIONS_OUTGOING,

    BIDIRECTIONAL_NUMBER_OF_RELATION_ATTRIBUTE_INVOCATIONS,

    BIDIRECTIONAL_NUMBER_OF_RELATION_METHOD_INVOCATIONS,

    BIDIRECTIONAL_NUMBER_OF_RELATION_PACKAGE_IMPORTS,

    BIDIRECTIONAL_NUMBER_OF_RELATION_CONSTRUCTOR_INVOCATIONS
}
