CREATE TABLE STATIC_INFO_ATTRIBUTE_DECLARATION
(
    static_info_id       BIGINT NOT NULL REFERENCES STATIC_INFO (id),
    attribute_declaration_id BIGINT NOT NULL REFERENCES ATTRIBUTE_DECLARATION (id) UNIQUE
)