CREATE TABLE STATIC_INFO_CONSTRUCTOR_DECLARATION
(
    static_info_id             BIGINT NOT NULL REFERENCES STATIC_INFO (id),
    constructor_declaration_id BIGINT NOT NULL REFERENCES CONSTRUCTOR_DECLARATION (id) UNIQUE
)