CREATE TABLE SOURCE_FILE
(
    id          BIGINT  NOT NULL GENERATED ALWAYS AS IDENTITY (START 1) PRIMARY KEY,
    snapshot_id BIGINT  NOT NULL REFERENCES SNAPSHOT (id),
    file_hash   VARCHAR NOT NULL,
    file_path   VARCHAR NOT NULL
)