CREATE TABLE CLASS_STRUCTURE_EXTERNAL_CONSTRUCTOR_INVOCATION
(
    class_structure_id   BIGINT NOT NULL REFERENCES CLASS_STRUCTURE (id),
    constructor_invocation_id BIGINT NOT NULL REFERENCES CONSTRUCTOR_INVOCATION (id) UNIQUE
)