CREATE TABLE SOURCE_FILE
(
    id BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY (START 1) PRIMARY KEY ,
    snapshot_id BIGINT NOT NULL REFERENCES SNAPSHOT(id),
    file_hash INT NOT NULL,
    file_name VARCHAR NOT NULL
)