CREATE TABLE METHOD_DECLARATION_PARAMETER_DECLARATION
(
    method_declaration_id    BIGINT NOT NULL REFERENCES METHOD_DECLARATION (id),
    parameter_declaration_id BIGINT NOT NULL REFERENCES PARAMETER_DECLARATION (id) UNIQUE
)