CREATE TABLE STATIC_INFO_IMPORT_DECLARATION
(
    static_info_id        BIGINT NOT NULL REFERENCES STATIC_INFO (id),
    import_declaration_id BIGINT NOT NULL REFERENCES IMPORT_DECLARATION (id) UNIQUE
)