CREATE TABLE CONSTRUCTOR_INVOCATION_PASSED_PARAMETER
(
    constructor_invocation_id BIGINT NOT NULL REFERENCES CONSTRUCTOR_INVOCATION (id),
    passed_parameter_id       BIGINT NOT NULL REFERENCES PASSED_PARAMETER (id) UNIQUE
)