CREATE TABLE STATIC_INFO_EXTERNAL_CONSTRUCTOR_INVOCATION
(
    static_info_id            BIGINT NOT NULL REFERENCES STATIC_INFO (id),
    constructor_invocation_id BIGINT NOT NULL REFERENCES CONSTRUCTOR_INVOCATION (id) UNIQUE
)