CREATE TABLE STATIC_INFO_EXTERNAL_ATTRIBUTE_INVOCATION
(
    static_info_id          BIGINT NOT NULL REFERENCES STATIC_INFO (id),
    attribute_invocation_id BIGINT NOT NULL REFERENCES ATTRIBUTE_INVOCATION (id) UNIQUE
)