CREATE TABLE MODIFIER_TYPE
(
    id   BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY (START 1) PRIMARY KEY,
    name VARCHAR NOT NULL UNIQUE
);

INSERT INTO MODIFIER_TYPE (name)
VALUES ('PUBLIC'),
       ('PROTECTED'),
       ('DEFAULT'),
       ('PRIVATE'),
       ('STATIC'),
       ('FINAL'),
       ('ABSTRACT'),
       ('UNRESOLVED');

DROP TABLE MODIFIER_TYPE;


