CREATE TABLE CONSTRUCTOR_DECLARATION_PARAMETER_DECLARATION
(
    constructor_declaration_id BIGINT NOT NULL REFERENCES CONSTRUCTOR_DECLARATION (id),
    parameter_declaration_id   BIGINT NOT NULL REFERENCES PARAMETER_DECLARATION (id) UNIQUE
)