CREATE TABLE CLASS_STRUCTURE_GLOBAL_METHOD_INVOCATION
(
    class_structure_id   BIGINT NOT NULL REFERENCES CLASS_STRUCTURE (id),
    method_invocation_id BIGINT NOT NULL REFERENCES METHOD_INVOCATION (id) UNIQUE
)