CREATE TABLE REPOSITORY
(
    repo_id BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY (START 1),
    repo_name VARCHAR NOT NULL,
    owner_id BIGINT NOT NULL,
    CONSTRAINT repositories_pkey PRIMARY KEY (repo_id),
    CONSTRAINT repositories_fkey FOREIGN KEY (owner_id)
        REFERENCES OWNER (owner_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE 
)