CREATE TABLE STATIC_INFO
(
    id                     BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY (START 1) PRIMARY KEY,
    package_declaration_id BIGINT NOT NULL REFERENCES PACKAGE_DECLARATION (id)
);

ALTER TABLE CLASS_STRUCTURE
    ADD COLUMN static_info_id BIGINT REFERENCES STATIC_INFO (id);

