CREATE TABLE CLASS_STRUCTURE_METHOD_DECLARATION
(
    class_structure_id    BIGINT NOT NULL REFERENCES CLASS_STRUCTURE (id),
    method_declaration_id BIGINT NOT NULL REFERENCES METHOD_DECLARATION (id) UNIQUE
)