CREATE TABLE STATIC_INFO_EXTERNAL_METHOD_INVOCATION
(
    static_info_id       BIGINT NOT NULL REFERENCES STATIC_INFO (id),
    method_invocation_id BIGINT NOT NULL REFERENCES METHOD_INVOCATION (id) UNIQUE
)