CREATE TABLE CLASS_STRUCTURE
(
    id                     BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY (START 1) PRIMARY KEY,
    package_declaration_id BIGINT NOT NULL REFERENCES PACKAGE_DECLARATION (id),
    class_metric_value_id  BIGINT NOT NULL REFERENCES CLASS_METRIC_VALUE (id)
)