CREATE TABLE OUTGOING_DEPENDENCE_INFO
(
    id             BIGINT  NOT NULL GENERATED ALWAYS AS IDENTITY (START 1) PRIMARY KEY,
    class_name     VARCHAR NOT NULL,
    static_info_id BIGINT  NOT NULL REFERENCES STATIC_INFO (id)
)