CREATE TABLE CLASS_STRUCTURE_ATTRIBUTE_DECLARATION
(
    class_structure_id       BIGINT NOT NULL REFERENCES CLASS_STRUCTURE (id),
    attribute_declaration_id BIGINT NOT NULL REFERENCES ATTRIBUTE_DECLARATION (id) UNIQUE
)